install:
    - sudo apt-get install tcl
    - wget --output-document=teacup http://teapot.activestate.com/application/name/teacup/ver/8.5.15.1.297892/arch/linux-glibc2.3-x86_64/file.exe
    - chmod +x teacup
    - sudo ./teacup setup /usr/bin/tclsh
    - ./teacup create "../lib/teapot"
    - sudo ./teacup link make "../lib/teapot" "/usr/bin/tclsh"

    - ./teacup install Itcl
    - sudo rm -r "/usr/lib/tcl-agate"
    - sudo git clone https://github.com/AngryLawyer/tcl-agate.git "/usr/lib/tcl-agate"
    - sudo rm -r "/usr/lib/SimpleTemplater"
    - sudo git clone https://github.com/cyrilthomas/SimpleTemplater.git "/usr/lib/SimpleTemplater"
script:
    - echo "puts \$auto_path" | tclsh
    - echo "puts \$tcl_pkgPath" | tclsh
    - ./runtests 
